POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Luffy",
  "email": "luffy@example.com",
  "password": "1234"
}

###
GET http://localhost:3000/api/usuarios

###
PUT http://localhost:3000/api/usuarios/1
Content-Type: application/json

{
  "nombre": "Monkey D. Luffy",
  "email": "nuevo@example.com",
  "password": "4321"
}

###
DELETE http://localhost:3000/api/usuarios/1

